location: 'pl' # us, uk, pl only supported. Note - use your actual location here, otherwise Nvidia will redirect you to their main page (so no cross-region support for this bot)
mode: 'checkout' # minimal, checkout and full. Minimal just refreshes the site and beeps when the card has been found. Checkout also adds the card to cart and fills all the addres + payment info. Full completes the order fro you.
card: '2060S' # 3080, 3090, 3070 and 2060S supported
address:
  first_name: 'Dave'
  last_name: 'Test'
  phone_number: '12345'
  email: '4@gmail.com'
  street: '5'
  apartment_number: 
  city: '6'
  state: ''
  postal_code: '7'
payment:
  method: 'cc' # only cc (credit card) supported.
  card_number: '123456' #no spacebars, eg. 1234567899123456
  cvv: '111' #eg. 123
  expiration_month: '12' #eg. 12 or 7
  expiration_year: '2022' #eg. 2023
